#!/bin/sh
cd src

find . -name .libs -type d -exec rm -r "{}" \;
find . \( -name Makefile.msc -o -name Makefile \) -type f -delete
find . \( -name "*.o" -o -name "*.lo" -o -name "*.la" -o -name "*.pyc" \) -type f -delete

find . -name "*.DS_Store" -type f -delete

rm -r -f autom4te.cache
rm -f libmonetdb5.so 
rm -f config.status config.log libtool stamp-h1 config.cache
rm -f monetdb_config.h
rm -f embedded/windows/monetdb_config.h

git ls-files . --others

cd ..



