# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.monetdb.org/Legal/MonetDBLicense
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2017 MonetDB B.V.
# All Rights Reserved.

MTSAFE

INCLUDES = ../mal/mal \
		   ../mal/modules \
		   ../mal/extras/rapi \
		   ../gdk \
		   ../common/stream \
		   ../common/utils \
		   ../common/options \
		   ../sql/include \
		   ../sql/server \
		   ../sql/common \
		   ../sql/storage \
		   ../sql/storage/bat \
		   ../sql/backends/monet5 \
			./inclinux \
			$(pcre_CFLAGS)

lib_embedded  = {
	SOURCES = embedded.c embedded.h
	VERSION = 1
	LIBS = ../gdk/libbat \
		$(pcre_LIBS) $(PSAPILIB) \
		$(SOCKET_LIBS) $(MALLOC_LIBS) $(DL_LIBS) $(PTHREAD_LIBS)
}

lib_embeddedjava  = {
	SOURCES = javaids.c javaids.h \
			converters.c converters.h \
			nl_cwi_monetdb_embedded_env_MonetDBEmbeddedDatabase.c nl_cwi_monetdb_embedded_env_MonetDBEmbeddedDatabase.h \
			nl_cwi_monetdb_embedded_env_MonetDBEmbeddedConnection.c nl_cwi_monetdb_embedded_env_MonetDBEmbeddedConnection.h \
			nl_cwi_monetdb_embedded_env_AbstractConnectionResult.c nl_cwi_monetdb_embedded_env_AbstractConnectionResult.h \
			nl_cwi_monetdb_embedded_mapping_NullMappings.c nl_cwi_monetdb_embedded_mapping_NullMappings.h \
			nl_cwi_monetdb_embedded_tables_MonetDBTable.c nl_cwi_monetdb_embedded_tables_MonetDBTable.h \
			nl_cwi_monetdb_embedded_jdbc_JDBCEmbeddedConnection.c nl_cwi_monetdb_embedded_jdbc_JDBCEmbeddedConnection.h
	VERSION = 1
	LIBS = libembedded \
			../gdk/libbat \
			$(pcre_LIBS) $(PSAPILIB) \
			$(SOCKET_LIBS) $(MALLOC_LIBS) $(DL_LIBS) $(PTHREAD_LIBS)
}
