/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_cwi_monetdb_embedded_env_AbstractConnectionResult */

#ifndef _Included_nl_cwi_monetdb_embedded_env_AbstractConnectionResult
#define _Included_nl_cwi_monetdb_embedded_env_AbstractConnectionResult
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nl_cwi_monetdb_embedded_env_AbstractConnectionResult
 * Method:    closeResultImplementation
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nl_cwi_monetdb_embedded_env_AbstractConnectionResult_closeResultImplementation
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
