/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_cwi_monetdb_embedded_resultset_QueryResultSet */

#ifndef _Included_nl_cwi_monetdb_embedded_resultset_QueryResultSet
#define _Included_nl_cwi_monetdb_embedded_resultset_QueryResultSet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nl_cwi_monetdb_embedded_resultset_QueryResultSet
 * Method:    getColumnNamesInternal
 * Signature: (J[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_nl_cwi_monetdb_embedded_resultset_QueryResultSet_getColumnNamesInternal
  (JNIEnv *, jobject, jlong, jobjectArray);

/*
 * Class:     nl_cwi_monetdb_embedded_resultset_QueryResultSet
 * Method:    getColumnTypesInternal
 * Signature: (J[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_nl_cwi_monetdb_embedded_resultset_QueryResultSet_getColumnTypesInternal
  (JNIEnv *, jobject, jlong, jobjectArray);

/*
 * Class:     nl_cwi_monetdb_embedded_resultset_QueryResultSet
 * Method:    getMappingsInternal
 * Signature: (J[Lnl/cwi/monetdb/embedded/mapping/MonetDBToJavaMapping;)V
 */
JNIEXPORT void JNICALL Java_nl_cwi_monetdb_embedded_resultset_QueryResultSet_getMappingsInternal
  (JNIEnv *, jobject, jlong, jobjectArray);

/*
 * Class:     nl_cwi_monetdb_embedded_resultset_QueryResultSet
 * Method:    getColumnDigitsInternal
 * Signature: (J[I)V
 */
JNIEXPORT void JNICALL Java_nl_cwi_monetdb_embedded_resultset_QueryResultSet_getColumnDigitsInternal
  (JNIEnv *, jobject, jlong, jintArray);

/*
 * Class:     nl_cwi_monetdb_embedded_resultset_QueryResultSet
 * Method:    getColumnScalesInternal
 * Signature: (J[I)V
 */
JNIEXPORT void JNICALL Java_nl_cwi_monetdb_embedded_resultset_QueryResultSet_getColumnScalesInternal
  (JNIEnv *, jobject, jlong, jintArray);

/*
 * Class:     nl_cwi_monetdb_embedded_resultset_QueryResultSet
 * Method:    getByteByColumnAndRowInternal
 * Signature: (JII)B
 */
JNIEXPORT jbyte JNICALL Java_nl_cwi_monetdb_embedded_resultset_QueryResultSet_getByteByColumnAndRowInternal
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_resultset_QueryResultSet
 * Method:    getShortByColumnAndRowInternal
 * Signature: (JII)S
 */
JNIEXPORT jshort JNICALL Java_nl_cwi_monetdb_embedded_resultset_QueryResultSet_getShortByColumnAndRowInternal
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_resultset_QueryResultSet
 * Method:    getIntegerByColumnAndRowInternal
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_nl_cwi_monetdb_embedded_resultset_QueryResultSet_getIntegerByColumnAndRowInternal
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_resultset_QueryResultSet
 * Method:    getLongByColumnAndRowInternal
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_nl_cwi_monetdb_embedded_resultset_QueryResultSet_getLongByColumnAndRowInternal
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_resultset_QueryResultSet
 * Method:    getFloatByColumnAndRowInternal
 * Signature: (JII)F
 */
JNIEXPORT jfloat JNICALL Java_nl_cwi_monetdb_embedded_resultset_QueryResultSet_getFloatByColumnAndRowInternal
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_resultset_QueryResultSet
 * Method:    getDoubleByColumnAndRowInternal
 * Signature: (JII)D
 */
JNIEXPORT jdouble JNICALL Java_nl_cwi_monetdb_embedded_resultset_QueryResultSet_getDoubleByColumnAndRowInternal
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_resultset_QueryResultSet
 * Method:    getStringByColumnAndRowInternal
 * Signature: (JII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nl_cwi_monetdb_embedded_resultset_QueryResultSet_getStringByColumnAndRowInternal
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_resultset_QueryResultSet
 * Method:    getDateByColumnAndRowInternal
 * Signature: (JII)Ljava/sql/Date;
 */
JNIEXPORT jobject JNICALL Java_nl_cwi_monetdb_embedded_resultset_QueryResultSet_getDateByColumnAndRowInternal
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_resultset_QueryResultSet
 * Method:    getTimestampByColumnAndRowInternal
 * Signature: (JII)Ljava/sql/Timestamp;
 */
JNIEXPORT jobject JNICALL Java_nl_cwi_monetdb_embedded_resultset_QueryResultSet_getTimestampByColumnAndRowInternal
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_resultset_QueryResultSet
 * Method:    getTimeByColumnAndRowInternal
 * Signature: (JII)Ljava/sql/Time;
 */
JNIEXPORT jobject JNICALL Java_nl_cwi_monetdb_embedded_resultset_QueryResultSet_getTimeByColumnAndRowInternal
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_resultset_QueryResultSet
 * Method:    getDecimalByColumnAndRowInternal
 * Signature: (JII)Ljava/math/BigDecimal;
 */
JNIEXPORT jobject JNICALL Java_nl_cwi_monetdb_embedded_resultset_QueryResultSet_getDecimalByColumnAndRowInternal
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_resultset_QueryResultSet
 * Method:    getBlobByColumnAndRowInternal
 * Signature: (JII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_nl_cwi_monetdb_embedded_resultset_QueryResultSet_getBlobByColumnAndRowInternal
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_resultset_QueryResultSet
 * Method:    getBooleanColumnByIndexInternal
 * Signature: (JI[ZII)V
 */
JNIEXPORT void JNICALL Java_nl_cwi_monetdb_embedded_resultset_QueryResultSet_getBooleanColumnByIndexInternal
  (JNIEnv *, jobject, jlong, jint, jbooleanArray, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_resultset_QueryResultSet
 * Method:    getByteColumnByIndexInternal
 * Signature: (JI[BII)V
 */
JNIEXPORT void JNICALL Java_nl_cwi_monetdb_embedded_resultset_QueryResultSet_getByteColumnByIndexInternal
  (JNIEnv *, jobject, jlong, jint, jbyteArray, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_resultset_QueryResultSet
 * Method:    getShortColumnByIndexInternal
 * Signature: (JI[SII)V
 */
JNIEXPORT void JNICALL Java_nl_cwi_monetdb_embedded_resultset_QueryResultSet_getShortColumnByIndexInternal
  (JNIEnv *, jobject, jlong, jint, jshortArray, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_resultset_QueryResultSet
 * Method:    getIntColumnByIndexInternal
 * Signature: (JI[III)V
 */
JNIEXPORT void JNICALL Java_nl_cwi_monetdb_embedded_resultset_QueryResultSet_getIntColumnByIndexInternal
  (JNIEnv *, jobject, jlong, jint, jintArray, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_resultset_QueryResultSet
 * Method:    getLongColumnByIndexInternal
 * Signature: (JI[JII)V
 */
JNIEXPORT void JNICALL Java_nl_cwi_monetdb_embedded_resultset_QueryResultSet_getLongColumnByIndexInternal
  (JNIEnv *, jobject, jlong, jint, jlongArray, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_resultset_QueryResultSet
 * Method:    getFloatColumnByIndexInternal
 * Signature: (JI[FII)V
 */
JNIEXPORT void JNICALL Java_nl_cwi_monetdb_embedded_resultset_QueryResultSet_getFloatColumnByIndexInternal
  (JNIEnv *, jobject, jlong, jint, jfloatArray, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_resultset_QueryResultSet
 * Method:    getDoubleColumnByIndexInternal
 * Signature: (JI[DII)V
 */
JNIEXPORT void JNICALL Java_nl_cwi_monetdb_embedded_resultset_QueryResultSet_getDoubleColumnByIndexInternal
  (JNIEnv *, jobject, jlong, jint, jdoubleArray, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_resultset_QueryResultSet
 * Method:    getStringColumnByIndexInternal
 * Signature: (JI[Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_nl_cwi_monetdb_embedded_resultset_QueryResultSet_getStringColumnByIndexInternal
  (JNIEnv *, jobject, jlong, jint, jobjectArray, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_resultset_QueryResultSet
 * Method:    getDateColumnByIndexInternal
 * Signature: (JI[Ljava/sql/Date;II)V
 */
JNIEXPORT void JNICALL Java_nl_cwi_monetdb_embedded_resultset_QueryResultSet_getDateColumnByIndexInternal
  (JNIEnv *, jobject, jlong, jint, jobjectArray, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_resultset_QueryResultSet
 * Method:    getTimestampColumnByIndexInternal
 * Signature: (JI[Ljava/sql/Timestamp;II)V
 */
JNIEXPORT void JNICALL Java_nl_cwi_monetdb_embedded_resultset_QueryResultSet_getTimestampColumnByIndexInternal
  (JNIEnv *, jobject, jlong, jint, jobjectArray, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_resultset_QueryResultSet
 * Method:    getTimeColumnByIndexInternal
 * Signature: (JI[Ljava/sql/Time;II)V
 */
JNIEXPORT void JNICALL Java_nl_cwi_monetdb_embedded_resultset_QueryResultSet_getTimeColumnByIndexInternal
  (JNIEnv *, jobject, jlong, jint, jobjectArray, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_resultset_QueryResultSet
 * Method:    getBlobColumnByIndexInternal
 * Signature: (JI[[BII)V
 */
JNIEXPORT void JNICALL Java_nl_cwi_monetdb_embedded_resultset_QueryResultSet_getBlobColumnByIndexInternal
  (JNIEnv *, jobject, jlong, jint, jobjectArray, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_resultset_QueryResultSet
 * Method:    getDecimalColumnByIndexInternal
 * Signature: (JI[Ljava/math/BigDecimal;II)V
 */
JNIEXPORT void JNICALL Java_nl_cwi_monetdb_embedded_resultset_QueryResultSet_getDecimalColumnByIndexInternal
  (JNIEnv *, jobject, jlong, jint, jobjectArray, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_resultset_QueryResultSet
 * Method:    getColumnNullMappingsByIndexInternal
 * Signature: (JII[Z)V
 */
JNIEXPORT void JNICALL Java_nl_cwi_monetdb_embedded_resultset_QueryResultSet_getColumnNullMappingsByIndexInternal
  (JNIEnv *, jobject, jlong, jint, jint, jbooleanArray);

/*
 * Class:     nl_cwi_monetdb_embedded_resultset_QueryResultSet
 * Method:    mapColumnToObjectByIndexInternal
 * Signature: (JII[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_nl_cwi_monetdb_embedded_resultset_QueryResultSet_mapColumnToObjectByIndexInternal
  (JNIEnv *, jobject, jlong, jint, jint, jobjectArray);

/*
 * Class:     nl_cwi_monetdb_embedded_resultset_QueryResultSet
 * Method:    freeResultSet
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_nl_cwi_monetdb_embedded_resultset_QueryResultSet_freeResultSet
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
