/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_cwi_monetdb_embedded_env_MonetDBEmbeddedDatabase */

#ifndef _Included_nl_cwi_monetdb_embedded_env_MonetDBEmbeddedDatabase
#define _Included_nl_cwi_monetdb_embedded_env_MonetDBEmbeddedDatabase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nl_cwi_monetdb_embedded_env_MonetDBEmbeddedDatabase
 * Method:    StartDatabaseInternal
 * Signature: (Ljava/lang/String;ZZ)Lnl/cwi/monetdb/embedded/env/MonetDBEmbeddedDatabase;
 */
JNIEXPORT jobject JNICALL Java_nl_cwi_monetdb_embedded_env_MonetDBEmbeddedDatabase_StartDatabaseInternal
  (JNIEnv *, jclass, jstring, jboolean, jboolean);

/*
 * Class:     nl_cwi_monetdb_embedded_env_MonetDBEmbeddedDatabase
 * Method:    stopDatabaseInternal
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nl_cwi_monetdb_embedded_env_MonetDBEmbeddedDatabase_stopDatabaseInternal
  (JNIEnv *, jobject);

/*
 * Class:     nl_cwi_monetdb_embedded_env_MonetDBEmbeddedDatabase
 * Method:    createConnectionInternal
 * Signature: ()Lnl/cwi/monetdb/embedded/env/MonetDBEmbeddedConnection;
 */
JNIEXPORT jobject JNICALL Java_nl_cwi_monetdb_embedded_env_MonetDBEmbeddedDatabase_createConnectionInternal
  (JNIEnv *, jobject);

/*
 * Class:     nl_cwi_monetdb_embedded_env_MonetDBEmbeddedDatabase
 * Method:    createJDBCEmbeddedConnectionInternal
 * Signature: ()Lnl/cwi/monetdb/mcl/connection/embedded/JDBCEmbeddedConnection;
 */
JNIEXPORT jobject JNICALL Java_nl_cwi_monetdb_embedded_env_MonetDBEmbeddedDatabase_createJDBCEmbeddedConnectionInternal
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
