/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_cwi_monetdb_embedded_env_MonetDBEmbeddedPreparedStatement */

#ifndef _Included_nl_cwi_monetdb_embedded_env_MonetDBEmbeddedPreparedStatement
#define _Included_nl_cwi_monetdb_embedded_env_MonetDBEmbeddedPreparedStatement
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nl_cwi_monetdb_embedded_env_MonetDBEmbeddedPreparedStatement
 * Method:    freePreparedStatement
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_nl_cwi_monetdb_embedded_env_MonetDBEmbeddedPreparedStatement_freePreparedStatement
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
