/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_cwi_monetdb_embedded_mapping_NullMappings */

#ifndef _Included_nl_cwi_monetdb_embedded_mapping_NullMappings
#define _Included_nl_cwi_monetdb_embedded_mapping_NullMappings
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nl_cwi_monetdb_embedded_mapping_NullMappings
 * Method:    GetBooleanNullConstant
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_nl_cwi_monetdb_embedded_mapping_NullMappings_GetBooleanNullConstant
  (JNIEnv *, jclass);

/*
 * Class:     nl_cwi_monetdb_embedded_mapping_NullMappings
 * Method:    GetByteNullConstant
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_nl_cwi_monetdb_embedded_mapping_NullMappings_GetByteNullConstant
  (JNIEnv *, jclass);

/*
 * Class:     nl_cwi_monetdb_embedded_mapping_NullMappings
 * Method:    GetShortNullConstant
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_nl_cwi_monetdb_embedded_mapping_NullMappings_GetShortNullConstant
  (JNIEnv *, jclass);

/*
 * Class:     nl_cwi_monetdb_embedded_mapping_NullMappings
 * Method:    GetIntNullConstant
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nl_cwi_monetdb_embedded_mapping_NullMappings_GetIntNullConstant
  (JNIEnv *, jclass);

/*
 * Class:     nl_cwi_monetdb_embedded_mapping_NullMappings
 * Method:    GetLongNullConstant
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_nl_cwi_monetdb_embedded_mapping_NullMappings_GetLongNullConstant
  (JNIEnv *, jclass);

/*
 * Class:     nl_cwi_monetdb_embedded_mapping_NullMappings
 * Method:    GetFloatNullConstant
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_nl_cwi_monetdb_embedded_mapping_NullMappings_GetFloatNullConstant
  (JNIEnv *, jclass);

/*
 * Class:     nl_cwi_monetdb_embedded_mapping_NullMappings
 * Method:    GetDoubleNullConstant
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_nl_cwi_monetdb_embedded_mapping_NullMappings_GetDoubleNullConstant
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
