/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_cwi_monetdb_embedded_jdbc_EmbeddedDataBlockResponse */

#ifndef _Included_nl_cwi_monetdb_embedded_jdbc_EmbeddedDataBlockResponse
#define _Included_nl_cwi_monetdb_embedded_jdbc_EmbeddedDataBlockResponse
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nl_cwi_monetdb_embedded_jdbc_EmbeddedDataBlockResponse
 * Method:    getByteValueInternal
 * Signature: (JII)B
 */
JNIEXPORT jbyte JNICALL Java_nl_cwi_monetdb_embedded_jdbc_EmbeddedDataBlockResponse_getByteValueInternal
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_jdbc_EmbeddedDataBlockResponse
 * Method:    getShortValueInternal
 * Signature: (JII)S
 */
JNIEXPORT jshort JNICALL Java_nl_cwi_monetdb_embedded_jdbc_EmbeddedDataBlockResponse_getShortValueInternal
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_jdbc_EmbeddedDataBlockResponse
 * Method:    getIntValueInternal
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_nl_cwi_monetdb_embedded_jdbc_EmbeddedDataBlockResponse_getIntValueInternal
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_jdbc_EmbeddedDataBlockResponse
 * Method:    getLongValueInternal
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_nl_cwi_monetdb_embedded_jdbc_EmbeddedDataBlockResponse_getLongValueInternal
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_jdbc_EmbeddedDataBlockResponse
 * Method:    getFloatValueInternal
 * Signature: (JII)F
 */
JNIEXPORT jfloat JNICALL Java_nl_cwi_monetdb_embedded_jdbc_EmbeddedDataBlockResponse_getFloatValueInternal
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_jdbc_EmbeddedDataBlockResponse
 * Method:    getDoubleValueInternal
 * Signature: (JII)D
 */
JNIEXPORT jdouble JNICALL Java_nl_cwi_monetdb_embedded_jdbc_EmbeddedDataBlockResponse_getDoubleValueInternal
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_jdbc_EmbeddedDataBlockResponse
 * Method:    getStringValueInternal
 * Signature: (JII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nl_cwi_monetdb_embedded_jdbc_EmbeddedDataBlockResponse_getStringValueInternal
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_jdbc_EmbeddedDataBlockResponse
 * Method:    getDateValueInternal
 * Signature: (JII)Ljava/sql/Date;
 */
JNIEXPORT jobject JNICALL Java_nl_cwi_monetdb_embedded_jdbc_EmbeddedDataBlockResponse_getDateValueInternal
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_jdbc_EmbeddedDataBlockResponse
 * Method:    getTimestampValueInternal
 * Signature: (JII)Ljava/sql/Timestamp;
 */
JNIEXPORT jobject JNICALL Java_nl_cwi_monetdb_embedded_jdbc_EmbeddedDataBlockResponse_getTimestampValueInternal
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_jdbc_EmbeddedDataBlockResponse
 * Method:    getTimeValueInternal
 * Signature: (JII)Ljava/sql/Time;
 */
JNIEXPORT jobject JNICALL Java_nl_cwi_monetdb_embedded_jdbc_EmbeddedDataBlockResponse_getTimeValueInternal
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_jdbc_EmbeddedDataBlockResponse
 * Method:    getDecimalValueInternal
 * Signature: (JII)Ljava/math/BigDecimal;
 */
JNIEXPORT jobject JNICALL Java_nl_cwi_monetdb_embedded_jdbc_EmbeddedDataBlockResponse_getDecimalValueInternal
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_jdbc_EmbeddedDataBlockResponse
 * Method:    getBlobValueInternal
 * Signature: (JII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_nl_cwi_monetdb_embedded_jdbc_EmbeddedDataBlockResponse_getBlobValueInternal
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_jdbc_EmbeddedDataBlockResponse
 * Method:    getDateAsCalendarValueInternal
 * Signature: (JII)Ljava/util/Calendar;
 */
JNIEXPORT jobject JNICALL Java_nl_cwi_monetdb_embedded_jdbc_EmbeddedDataBlockResponse_getDateAsCalendarValueInternal
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_jdbc_EmbeddedDataBlockResponse
 * Method:    getTimestampAsCalendarValueInternal
 * Signature: (JII)Ljava/util/Calendar;
 */
JNIEXPORT jobject JNICALL Java_nl_cwi_monetdb_embedded_jdbc_EmbeddedDataBlockResponse_getTimestampAsCalendarValueInternal
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_jdbc_EmbeddedDataBlockResponse
 * Method:    getTimeAsCalendarValueInternal
 * Signature: (JII)Ljava/util/Calendar;
 */
JNIEXPORT jobject JNICALL Java_nl_cwi_monetdb_embedded_jdbc_EmbeddedDataBlockResponse_getTimeAsCalendarValueInternal
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_jdbc_EmbeddedDataBlockResponse
 * Method:    freeResultSet
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_nl_cwi_monetdb_embedded_jdbc_EmbeddedDataBlockResponse_freeResultSet
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
