/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_cwi_monetdb_embedded_env_MonetDBEmbeddedConnection */

#ifndef _Included_nl_cwi_monetdb_embedded_env_MonetDBEmbeddedConnection
#define _Included_nl_cwi_monetdb_embedded_env_MonetDBEmbeddedConnection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nl_cwi_monetdb_embedded_env_MonetDBEmbeddedConnection
 * Method:    getAutoCommitInternal
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_nl_cwi_monetdb_embedded_env_MonetDBEmbeddedConnection_getAutoCommitInternal
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_cwi_monetdb_embedded_env_MonetDBEmbeddedConnection
 * Method:    setAutoCommitInternal
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_nl_cwi_monetdb_embedded_env_MonetDBEmbeddedConnection_setAutoCommitInternal
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     nl_cwi_monetdb_embedded_env_MonetDBEmbeddedConnection
 * Method:    sendUpdateInternal
 * Signature: (JLjava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_nl_cwi_monetdb_embedded_env_MonetDBEmbeddedConnection_sendUpdateInternal
  (JNIEnv *, jobject, jlong, jstring, jboolean);

/*
 * Class:     nl_cwi_monetdb_embedded_env_MonetDBEmbeddedConnection
 * Method:    sendQueryInternal
 * Signature: (JLjava/lang/String;Z)Lnl/cwi/monetdb/embedded/resultset/QueryResultSet;
 */
JNIEXPORT jobject JNICALL Java_nl_cwi_monetdb_embedded_env_MonetDBEmbeddedConnection_sendQueryInternal
  (JNIEnv *, jobject, jlong, jstring, jboolean);

/*
 * Class:     nl_cwi_monetdb_embedded_env_MonetDBEmbeddedConnection
 * Method:    getMonetDBTableInternal
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Lnl/cwi/monetdb/embedded/tables/MonetDBTable;
 */
JNIEXPORT jobject JNICALL Java_nl_cwi_monetdb_embedded_env_MonetDBEmbeddedConnection_getMonetDBTableInternal
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     nl_cwi_monetdb_embedded_env_MonetDBEmbeddedConnection
 * Method:    closeConnectionInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_nl_cwi_monetdb_embedded_env_MonetDBEmbeddedConnection_closeConnectionInternal
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
