/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_cwi_monetdb_embedded_mapping_NullMappings */

#ifndef _Included_nl_cwi_monetdb_embedded_mapping_NullMappings
#define _Included_nl_cwi_monetdb_embedded_mapping_NullMappings
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nl_cwi_monetdb_embedded_mapping_NullMappings
 * Method:    getBooleanNullConstant
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_nl_cwi_monetdb_embedded_mapping_NullMappings_getBooleanNullConstant
  (JNIEnv *, jclass);

/*
 * Class:     nl_cwi_monetdb_embedded_mapping_NullMappings
 * Method:    getByteNullConstant
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_nl_cwi_monetdb_embedded_mapping_NullMappings_getByteNullConstant
  (JNIEnv *, jclass);

/*
 * Class:     nl_cwi_monetdb_embedded_mapping_NullMappings
 * Method:    getShortNullConstant
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_nl_cwi_monetdb_embedded_mapping_NullMappings_getShortNullConstant
  (JNIEnv *, jclass);

/*
 * Class:     nl_cwi_monetdb_embedded_mapping_NullMappings
 * Method:    getIntNullConstant
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nl_cwi_monetdb_embedded_mapping_NullMappings_getIntNullConstant
  (JNIEnv *, jclass);

/*
 * Class:     nl_cwi_monetdb_embedded_mapping_NullMappings
 * Method:    getLongNullConstant
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_nl_cwi_monetdb_embedded_mapping_NullMappings_getLongNullConstant
  (JNIEnv *, jclass);

/*
 * Class:     nl_cwi_monetdb_embedded_mapping_NullMappings
 * Method:    getFloatNullConstant
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_nl_cwi_monetdb_embedded_mapping_NullMappings_getFloatNullConstant
  (JNIEnv *, jclass);

/*
 * Class:     nl_cwi_monetdb_embedded_mapping_NullMappings
 * Method:    getDoubleNullConstant
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_nl_cwi_monetdb_embedded_mapping_NullMappings_getDoubleNullConstant
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
