  /* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_cwi_monetdb_embedded_tables_MonetDBTable */

#ifndef _Included_nl_cwi_monetdb_embedded_tables_MonetDBTable
#define _Included_nl_cwi_monetdb_embedded_tables_MonetDBTable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nl_cwi_monetdb_embedded_tables_MonetDBTable
 * Method:    getNumberOfColumns
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nl_cwi_monetdb_embedded_tables_MonetDBTable_getNumberOfColumns
  (JNIEnv *, jobject);

/*
 * Class:     nl_cwi_monetdb_embedded_tables_MonetDBTable
 * Method:    getColumnNamesInternal
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_nl_cwi_monetdb_embedded_tables_MonetDBTable_getColumnNamesInternal
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     nl_cwi_monetdb_embedded_tables_MonetDBTable
 * Method:    getColumnTypesInternal
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_nl_cwi_monetdb_embedded_tables_MonetDBTable_getColumnTypesInternal
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     nl_cwi_monetdb_embedded_tables_MonetDBTable
 * Method:    getMappingsInternal
 * Signature: ([Lnl/cwi/monetdb/embedded/mapping/MonetDBToJavaMapping;)V
 */
JNIEXPORT void JNICALL Java_nl_cwi_monetdb_embedded_tables_MonetDBTable_getMappingsInternal
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     nl_cwi_monetdb_embedded_tables_MonetDBTable
 * Method:    getColumnDigitsInternal
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_nl_cwi_monetdb_embedded_tables_MonetDBTable_getColumnDigitsInternal
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     nl_cwi_monetdb_embedded_tables_MonetDBTable
 * Method:    getColumnScalesInternal
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_nl_cwi_monetdb_embedded_tables_MonetDBTable_getColumnScalesInternal
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     nl_cwi_monetdb_embedded_tables_MonetDBTable
 * Method:    getColumnNullableIndexesInternal
 * Signature: ([Z)V
 */
JNIEXPORT void JNICALL Java_nl_cwi_monetdb_embedded_tables_MonetDBTable_getColumnNullableIndexesInternal
  (JNIEnv *, jobject, jbooleanArray);

/*
 * Class:     nl_cwi_monetdb_embedded_tables_MonetDBTable
 * Method:    getColumnDefaultValuesInternal
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_nl_cwi_monetdb_embedded_tables_MonetDBTable_getColumnDefaultValuesInternal
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     nl_cwi_monetdb_embedded_tables_MonetDBTable
 * Method:    getColumnMetadataByIndex
 * Signature: (I)Lnl/cwi/monetdb/embedded/tables/MonetDBTableColumn;
 */
JNIEXPORT jobject JNICALL Java_nl_cwi_monetdb_embedded_tables_MonetDBTable_getColumnMetadataByIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_tables_MonetDBTable
 * Method:    getColumnMetadataByName
 * Signature: (Ljava/lang/String;)Lnl/cwi/monetdb/embedded/tables/MonetDBTableColumn;
 */
JNIEXPORT jobject JNICALL Java_nl_cwi_monetdb_embedded_tables_MonetDBTable_getColumnMetadataByName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     nl_cwi_monetdb_embedded_tables_MonetDBTable
 * Method:    getAllColumnsMetadata
 * Signature: ()[Lnl/cwi/monetdb/embedded/tables/MonetDBTableColumn;
 */
JNIEXPORT jobjectArray JNICALL Java_nl_cwi_monetdb_embedded_tables_MonetDBTable_getAllColumnsMetadata
  (JNIEnv *, jobject);

/*
 * Class:     nl_cwi_monetdb_embedded_tables_MonetDBTable
 * Method:    appendColumnsInternal
 * Signature: ([Ljava/lang/Object;[II)I
 */
JNIEXPORT jint JNICALL Java_nl_cwi_monetdb_embedded_tables_MonetDBTable_appendColumnsInternal
  (JNIEnv *, jobject, jobjectArray, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
