/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_cwi_monetdb_embedded_tables_MonetDBTable */

#ifndef _Included_nl_cwi_monetdb_embedded_tables_MonetDBTable
#define _Included_nl_cwi_monetdb_embedded_tables_MonetDBTable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nl_cwi_monetdb_embedded_tables_MonetDBTable
 * Method:    getNumberOfColumns
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nl_cwi_monetdb_embedded_tables_MonetDBTable_getNumberOfColumns
  (JNIEnv *, jobject);

/*
 * Class:     nl_cwi_monetdb_embedded_tables_MonetDBTable
 * Method:    getColumnNames
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_nl_cwi_monetdb_embedded_tables_MonetDBTable_getColumnNames
  (JNIEnv *, jobject);

/*
 * Class:     nl_cwi_monetdb_embedded_tables_MonetDBTable
 * Method:    getColumnTypes
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_nl_cwi_monetdb_embedded_tables_MonetDBTable_getColumnTypes
  (JNIEnv *, jobject);

/*
 * Class:     nl_cwi_monetdb_embedded_tables_MonetDBTable
 * Method:    getMappings
 * Signature: ()[Lnl/cwi/monetdb/embedded/mapping/MonetDBToJavaMapping;
 */
JNIEXPORT jobjectArray JNICALL Java_nl_cwi_monetdb_embedded_tables_MonetDBTable_getMappings
  (JNIEnv *, jobject);

/*
 * Class:     nl_cwi_monetdb_embedded_tables_MonetDBTable
 * Method:    getColumnDigits
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_nl_cwi_monetdb_embedded_tables_MonetDBTable_getColumnDigits
  (JNIEnv *, jobject);

/*
 * Class:     nl_cwi_monetdb_embedded_tables_MonetDBTable
 * Method:    getColumnScales
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_nl_cwi_monetdb_embedded_tables_MonetDBTable_getColumnScales
  (JNIEnv *, jobject);

/*
 * Class:     nl_cwi_monetdb_embedded_tables_MonetDBTable
 * Method:    getColumnNullableIndexes
 * Signature: ()[Z
 */
JNIEXPORT jbooleanArray JNICALL Java_nl_cwi_monetdb_embedded_tables_MonetDBTable_getColumnNullableIndexes
  (JNIEnv *, jobject);

/*
 * Class:     nl_cwi_monetdb_embedded_tables_MonetDBTable
 * Method:    getColumnDefaultValues
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_nl_cwi_monetdb_embedded_tables_MonetDBTable_getColumnDefaultValues
  (JNIEnv *, jobject);

/*
 * Class:     nl_cwi_monetdb_embedded_tables_MonetDBTable
 * Method:    getColumnMetadataByIndex
 * Signature: (I)Lnl/cwi/monetdb/embedded/tables/MonetDBTableColumn;
 */
JNIEXPORT jobject JNICALL Java_nl_cwi_monetdb_embedded_tables_MonetDBTable_getColumnMetadataByIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     nl_cwi_monetdb_embedded_tables_MonetDBTable
 * Method:    getColumnMetadataByName
 * Signature: (Ljava/lang/String;)Lnl/cwi/monetdb/embedded/tables/MonetDBTableColumn;
 */
JNIEXPORT jobject JNICALL Java_nl_cwi_monetdb_embedded_tables_MonetDBTable_getColumnMetadataByName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     nl_cwi_monetdb_embedded_tables_MonetDBTable
 * Method:    getAllColumnsMetadata
 * Signature: ()[Lnl/cwi/monetdb/embedded/tables/MonetDBTableColumn;
 */
JNIEXPORT jobjectArray JNICALL Java_nl_cwi_monetdb_embedded_tables_MonetDBTable_getAllColumnsMetadata
  (JNIEnv *, jobject);

/*
 * Class:     nl_cwi_monetdb_embedded_tables_MonetDBTable
 * Method:    appendColumnsInternal
 * Signature: ([Ljava/lang/Object;[II)I
 */
JNIEXPORT jint JNICALL Java_nl_cwi_monetdb_embedded_tables_MonetDBTable_appendColumnsInternal
  (JNIEnv *, jobject, jobjectArray, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
