# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2016 MonetDB B.V.
	   
		   
INCLUDES = ../../common/options \
	../../common/stream \
	../../common/utils \
	../../gdk \
	../../ \
	../mal \
	../../clients/mapilib \
	$(pcre_CFLAGS) $(zlib_CFLAGS) $(BZIP_INCS) $(MSGCONTROL_FLAGS) $(openssl_CFLAGS)
   
		   
MTSAFE

lib_modules = {
	NOINST
	SOURCES = \
		blob.c blob.h \
		mtime.c mtime.h \
		str.c str.h \
		aggr.c \
		algebra.c algebra.h \
		bat5.c bat5.h \
		batmmath.c batmmath.h \
		batstr.c \
		group.c group.h \
		mmath.c mmath.h \
		batExtensions.c batExtensions.h \
		orderidx.c orderidx.h \
		iterator.c  iterator.h \
		projectionpath.c  projectionpath.h \
		language.c language.h \
		mat.c mat.h \
		mkey.c mkey.h \
		manifold.c manifold.h \
		pcre.c \
		profiler.c profiler.h \
		querylog.c querylog.h \
		sysmon.c sysmon.h \
		tablet.c tablet.h \
		sample.c sample.h \
		calc.c batcalc.c
	}

headers_mal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = \
		blob.mal \
		mtime.mal \
		str.mal \
		bat5.mal algebra.mal \
		mmath.mal batstr.mal \
		batmmath.mal \
		group.mal aggr.mal \
		language.mal mal_init.mal \
		profiler.mal batExtensions.mal orderidx.mal \
		mkey.mal manifold.mal \
		iterator.mal \
		pcre.mal mat.mal \
		sample.mal \
		batmtime.mal querylog.mal sysmon.mal
	}
		
headers_hge = {
	COND = HAVE_HGE
	HEADERS = mal
	DIR = libdir/monetdb5/autoload
	SOURCES = 00_aggr_hge.mal 00_calc_hge.mal 00_batcalc_hge.mal \
		00_iterator_hge.mal 00_language_hge.mal \
		00_mkey_hge.mal 00_batExtensions_hge.mal
}


headers_auto = {
	HEADERS = mal
	DIR = libdir/monetdb5/autoload
	SOURCES = 01_calc.mal 01_batcalc.mal
}


EXTRA_DIST = aggr.mal 00_aggr_hge.mal group.mal algebra.mal \
    batExtensions.mal iterator.mal \
	mal_init.mal mkey.mal manifold.mal pcre.mal \
	tablet.mal tablet.h sample.mal orderidx.mal \
	mat.mal \
	batmtime.mal querylog.mal sysmon.mal \
	01_calc.mal 01_batcalc.mal \
	00_calc_hge.mal 00_batcalc_hge.mal \
	00_iterator_hge.mal 00_language_hge.mal \
	00_mkey_hge.mal 00_batExtensions_hge.mal

		
		
		