# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2016 MonetDB B.V.

INCLUDES = ../../mal \
		   ../atoms \
		   ../../../common/options \
		   ../../../common/stream \
		   ../../../gdk

MTSAFE

lib_kernel = {
	NOINST
	SOURCES = \
		aggr.c \
		algebra.c algebra.h \
		bat5.c bat5.h \
		batmmath.c batmmath.h \
		batstr.c \
		group.c group.h \
		mmath.c mmath.h
}

headers_mal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = bat5.mal algebra.mal \
		mmath.mal batstr.mal \
		batmmath.mal \
		group.mal aggr.mal
}

headers_hge = {
	COND = HAVE_HGE
	HEADERS = mal
	DIR = libdir/monetdb5/autoload
	SOURCES = 00_aggr_hge.mal
}

EXTRA_DIST = aggr.mal 00_aggr_hge.mal group.mal algebra.mal

