#!/usr/bin/env sh

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2016 MonetDB B.V.

if [ "$1" ] ; then
	echo '
This script ("./de-bootstrap") can be used to clean up the source tree, 
i.e., to remove all files that were created by "./bootstrap".

"./de-bootstrap" first lists all files that are to be removed and 
asks the user for confirmation before actually removing the files.
'
	exit
fi

if [ ! -d ../.git ] ; then
	echo '
This script ("./de-bootstrap") must be called in top-level directory of
MonetDB'\''s GitHub source clone.
'
	exit 1
fi

git clean -f -d -x {\*\*Makefile.\*,\*\*.pyc,aclocal.m4,acout.in,autom4te.cache,buildtools/conf/{config.{guess,sub},install-sh,ltmain.sh,l[ti]\*.m4,missing,ylwrap},configure{,.ac},{doc,install}.lst,monetdb_config.h.in}

