SUBDIRS = common gdk mal sql embedded HAVE_EMBEDDED_R?mapisplit
EXTRA_DIST = configure configure.ac configure.ag libversions
headers_config = {
DIR = includedir/monetdb
HEADERS = h
SOURCES = monetdb_config.h
}
