SUBDIRS = buildtools common gdk monetdb5 sql embedded
EXTRA_DIST = configure configure.ac configure.ag libversions
headers_config = {
DIR = includedir/monetdb
HEADERS = h
SOURCES = monetdb_config.h
}
