# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2016 MonetDB B.V.

INCLUDES = ../../mal \
		   ../../../common/options \
		   ../../../common/stream \
		   ../../../common/utils \
		   ../../../gdk
		   
MTSAFE

lib_atoms = {
	NOINST
	SOURCES = \
		blob.c blob.h \
		mtime.c mtime.h \
		str.c str.h \
		streams.c streams.h
}

headers_mal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = \
		blob.mal \
		mtime.mal \
		str.mal \
		streams.mal
		}